# Generated by Django 5.2.2 on 2025-06-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
    ]
