# Generated by Django 5.2.2 on 2025-07-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_brand_alter_product_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='stock',
        ),
    ]
