# Generated by Django 5.2.2 on 2025-07-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_stock_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit_type',
            field=models.CharField(choices=[('weight(kg)', 'weight(KG)'), ('count', 'count')], default='weight(kg)', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
