# Generated by Django 5.2.2 on 2025-07-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_unit_type_alter_inventory_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='costomer_or_supplier_choices',
            new_name='role',
        ),
    ]
