# Generated by Django 5.2.2 on 2025-07-11 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_costomer_or_supplier_choices_order_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='role_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
