# Generated by Django 5.2.2 on 2025-07-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_order_role_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderLine',
        ),
    ]
